platform :ios, '8.0'
#use_frameworks!
inhibit_all_warnings!

target 'CJPopupViewDemo' do
    pod 'CQDemoKit',            '~> 0.5.6',     :subspecs => ['BaseVC', 'BaseUtil']
    
    pod 'CJPhotoBrowser',       :path => '../'
    pod 'CJPopupView',          :path => '../'
end

target 'CJPopupViewDemoTests' do
   
end
