platform :ios, '7.0'
#use_frameworks!

target 'CJPickerDemo' do
    pod 'CJRadio', '~> 1.0.3' #已包含pod 'CJPopupAction', '~> 1.4.2'
    pod 'JSONModel', '~> 1.7.0'
end

target 'CJPickerDemoTests' do
   
end
