platform :ios, '7.0'
#use_frameworks!

target 'CJRelatedPickerRichViewDemo' do
  pod 'RadioButtons', '~> 2.1.2'
  pod 'CJPopupView', '~> 1.3.0'
end

target 'CJRelatedPickerRichViewDemoTests' do
   
end
